apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Reports
    type: yesoreyeram-infinity-datasource
    uid: reports
    access: proxy
    url: ""
    isDefault: false
    editable: false
    jsonData: {}
